# fly.toml app configuration file generated for api-parle on 2025-09-29T22:07:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-parle'
primary_region = 'gdl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
